### ISSUE TITLE
Broken submodule reference to HTTPParser

### ISSUE THREAD

**Issue by davidask** [Zewo/Zeal#1]
Getting this when checking out the submodules.

``` sh
fatal: reference is not a tree: b9efaa720b0b680e2140d1da7d6ffd9bfef4f57b
Unable to checkout 'b9efaa720b0b680e2140d1da7d6ffd9bfef4f57b' in submodule path 'HTTPParser'
```

**Comment by paulofaria** [comment]
How did that happened? I think it's fixed now. Check, and let me know, please?

**Comment by davidask** [comment]
Happened when running `git clone --recursive git@github.com:Zewo/Zeal.git`.
Tested, and it seems to be fixed!
